version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:
services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: lenger1117/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static/
      - media_volume:/app/media/

  frontend:
    env_file: .env
    image: lenger1117/kittygram_frontend
    depends_on:
      - backend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static/

  gateway:
    image: lenger1117/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
    ports:
      - 9000:80
    volumes:
      - static_volume:/static/
      - media_volume:/static/media/
